import { Transaction } from "../types/types";

export const transactions: Transaction[] = [
  {
    avatar: "bytewise.jpg",
    name: "Bytewise",
    category: "Bills",
    date: new Date("2024-09-16T14:30:00"),
    amount: 129.99,
  },
  {
    avatar: "daniel-carter.jpg",
    name: "Daniel Carter",
    category: "Entertainment",
    date: new Date("2024-09-17T20:15:00"),
    amount: 45.5,
  },
  {
    avatar: "ecofuel-energy.jpg",
    name: "Ecofuel Energy",
    category: "Bills",
    date: new Date("2024-09-18T09:45:00"),
    amount: 210.75,
  },
  {
    avatar: "elevate-education.jpg",
    name: "Elevate Education",
    category: "Bills",
    date: new Date("2024-09-19T16:00:00"),
    amount: -500.0, // Refund
  },
  {
    avatar: "ella-phillips.jpg",
    name: "Ella Phillips",
    category: "Personal Care",
    date: new Date("2024-09-20T11:30:00"),
    amount: 65.0,
  },
  {
    avatar: "emma-richardson.jpg",
    name: "Emma Richardson",
    category: "Dining Out",
    date: new Date("2024-09-21T19:00:00"),
    amount: 82.25,
  },
  {
    avatar: "ethan-clark.jpg",
    name: "Ethan Clark",
    category: "Entertainment",
    date: new Date("2024-09-22T14:45:00"),
    amount: 29.99,
  },
  {
    avatar: "flavor-fiesta.jpg",
    name: "Flavor Fiesta",
    category: "Dining Out",
    date: new Date("2024-09-23T13:15:00"),
    amount: 37.5,
  },
  {
    avatar: "green-plate-eatery.jpg",
    name: "Green Plate Eatery",
    category: "Dining Out",
    date: new Date("2024-09-24T20:30:00"),
    amount: 55.75,
  },
  {
    avatar: "harper-edwards.jpg",
    name: "Harper Edwards",
    category: "Personal Care",
    date: new Date("2024-09-25T10:00:00"),
    amount: 120.0,
  },
  {
    avatar: "james-thompson.jpg",
    name: "James Thompson",
    category: "Bills",
    date: new Date("2024-09-26T15:45:00"),
    amount: 89.99,
  },
  {
    avatar: "liam-hughes.jpg",
    name: "Liam Hughes",
    category: "Entertainment",
    date: new Date("2024-09-27T18:30:00"),
    amount: 15.99,
  },
  {
    avatar: "lily-ramirez.jpg",
    name: "Lily Ramirez",
    category: "Personal Care",
    date: new Date("2024-09-28T12:00:00"),
    amount: 75.0,
  },
  {
    avatar: "aqua-flow-utilities.jpg",
    name: "Aqua Flow Utilities",
    category: "Bills",
    date: new Date("2024-09-29T09:30:00"),
    amount: 65.25,
  },
  {
    avatar: "buzz-marketing-group.jpg",
    name: "Buzz Marketing Group",
    category: "Bills",
    date: new Date("2024-09-30T14:15:00"),
    amount: -250.0, // Payment received
  },
  {
    avatar: "pixel-playground.jpg",
    name: "Pixel Playground",
    category: "Entertainment",
    date: new Date("2024-10-01T19:45:00"),
    amount: 39.99,
  },
  {
    avatar: "rina-sato.jpg",
    name: "Rina Sato",
    category: "Dining Out",
    date: new Date("2024-10-02T13:30:00"),
    amount: 68.5,
  },
  {
    avatar: "savory-bites-bistro.jpg",
    name: "Savory Bites Bistro",
    category: "Dining Out",
    date: new Date("2024-10-03T20:00:00"),
    amount: 92.75,
  },
  {
    avatar: "sebastian-cook.jpg",
    name: "Sebastian Cook",
    category: "Personal Care",
    date: new Date("2024-10-04T11:15:00"),
    amount: 55.0,
  },
  {
    avatar: "serenity-spa-and-wellness.jpg",
    name: "Serenity Spa and Wellness",
    category: "Personal Care",
    date: new Date("2024-10-05T16:45:00"),
    amount: 150.0,
  },
  {
    avatar: "sofia-peterson.jpg",
    name: "Sofia Peterson",
    category: "Entertainment",
    date: new Date("2024-10-06T19:30:00"),
    amount: 25.99,
  },
  {
    avatar: "spark-electric-solutions.jpg",
    name: "Spark Electric Solutions",
    category: "Bills",
    date: new Date("2024-10-07T10:45:00"),
    amount: 135.5,
  },
  {
    avatar: "sun-park.jpg",
    name: "Sun Park",
    category: "Entertainment",
    date: new Date("2024-10-08T14:00:00"),
    amount: 12.99,
  },
  {
    avatar: "swift-ride-share.jpg",
    name: "Swift Ride Share",
    category: "Entertainment",
    date: new Date("2024-10-09T18:15:00"),
    amount: 22.5,
  },
  {
    avatar: "technova-innovations.jpg",
    name: "Technova Innovations",
    category: "Bills",
    date: new Date("2024-10-10T09:00:00"),
    amount: 299.99,
  },
  {
    avatar: "urban-services-hub.jpg",
    name: "Urban Services Hub",
    category: "Bills",
    date: new Date("2024-10-11T13:45:00"),
    amount: 75.25,
  },
  {
    avatar: "william-harris.jpg",
    name: "William Harris",
    category: "Dining Out",
    date: new Date("2024-10-12T20:30:00"),
    amount: 88.75,
  },
  {
    avatar: "yuna-kim.jpg",
    name: "Yuna Kim",
    category: "Personal Care",
    date: new Date("2024-10-13T15:15:00"),
    amount: 60.0,
  },
  {
    avatar: "mason-martinez.jpg",
    name: "Mason Martinez",
    category: "Entertainment",
    date: new Date("2024-10-14T19:00:00"),
    amount: 35.99,
  },
  {
    avatar: "nimbus-data-storage.jpg",
    name: "Nimbus Data Storage",
    category: "Bills",
    date: new Date("2024-10-15T10:30:00"),
    amount: 109.99,
  },
  {
    avatar: "bytewise.jpg",
    name: "Bytewise",
    category: "Bills",
    date: new Date("2024-10-16T14:45:00"),
    amount: -75.0, // Credit applied
  },
  {
    avatar: "daniel-carter.jpg",
    name: "Daniel Carter",
    category: "Dining Out",
    date: new Date("2024-10-17T18:30:00"),
    amount: 42.5,
  },
  {
    avatar: "ecofuel-energy.jpg",
    name: "Ecofuel Energy",
    category: "Bills",
    date: new Date("2024-10-18T09:15:00"),
    amount: 195.25,
  },
  {
    avatar: "elevate-education.jpg",
    name: "Elevate Education",
    category: "Bills",
    date: new Date("2024-10-19T13:00:00"),
    amount: 250.0,
  },
  {
    avatar: "ella-phillips.jpg",
    name: "Ella Phillips",
    category: "Personal Care",
    date: new Date("2024-10-20T16:45:00"),
    amount: 85.0,
  },
  {
    avatar: "emma-richardson.jpg",
    name: "Emma Richardson",
    category: "Entertainment",
    date: new Date("2024-10-21T20:15:00"),
    amount: 49.99,
  },
  {
    avatar: "ethan-clark.jpg",
    name: "Ethan Clark",
    category: "Dining Out",
    date: new Date("2024-10-22T12:30:00"),
    amount: 31.75,
  },
  {
    avatar: "flavor-fiesta.jpg",
    name: "Flavor Fiesta",
    category: "Dining Out",
    date: new Date("2024-10-23T19:45:00"),
    amount: 57.25,
  },
  {
    avatar: "green-plate-eatery.jpg",
    name: "Green Plate Eatery",
    category: "Dining Out",
    date: new Date("2024-10-24T13:15:00"),
    amount: 44.5,
  },
  {
    avatar: "harper-edwards.jpg",
    name: "Harper Edwards",
    category: "Entertainment",
    date: new Date("2024-10-25T18:00:00"),
    amount: 65.99,
  },
  {
    avatar: "james-thompson.jpg",
    name: "James Thompson",
    category: "Bills",
    date: new Date("2024-10-26T10:45:00"),
    amount: 120.0,
  },
  {
    avatar: "liam-hughes.jpg",
    name: "Liam Hughes",
    category: "Personal Care",
    date: new Date("2024-10-27T15:30:00"),
    amount: 40.0,
  },
  {
    avatar: "lily-ramirez.jpg",
    name: "Lily Ramirez",
    category: "Entertainment",
    date: new Date("2024-10-28T19:15:00"),
    amount: 28.99,
  },
  {
    avatar: "aqua-flow-utilities.jpg",
    name: "Aqua Flow Utilities",
    category: "Bills",
    date: new Date("2024-10-29T09:30:00"),
    amount: 85.75,
  },
  {
    avatar: "buzz-marketing-group.jpg",
    name: "Buzz Marketing Group",
    category: "Bills",
    date: new Date("2024-10-30T14:00:00"),
    amount: -300.0, // Payment received
  },
  {
    avatar: "pixel-playground.jpg",
    name: "Pixel Playground",
    category: "Entertainment",
    date: new Date("2024-10-31T17:45:00"),
    amount: 19.99,
  },
  {
    avatar: "rina-sato.jpg",
    name: "Rina Sato",
    category: "Dining Out",
    date: new Date("2024-11-01T12:15:00"),
    amount: 53.25,
  },
  {
    avatar: "savory-bites-bistro.jpg",
    name: "Savory Bites Bistro",
    category: "Dining Out",
    date: new Date("2024-11-02T20:30:00"),
    amount: 78.5,
  },
  {
    avatar: "mason-martinez.jpg",
    name: "Mason Martinez",
    category: "Dining Out",
    date: new Date("2024-08-15T18:30:00"),
    amount: 78.5,
  },
  {
    avatar: "nimbus-data-storage.jpg",
    name: "Nimbus Data Storage",
    category: "Bills",
    date: new Date("2024-07-22T09:15:00"),
    amount: 129.99,
  },
  {
    avatar: "bytewise.jpg",
    name: "Bytewise",
    category: "Entertainment",
    date: new Date("2024-08-03T20:45:00"),
    amount: 59.99,
  },
  {
    avatar: "daniel-carter.jpg",
    name: "Daniel Carter",
    category: "Personal Care",
    date: new Date("2024-07-18T14:00:00"),
    amount: 45.0,
  },
  {
    avatar: "ecofuel-energy.jpg",
    name: "Ecofuel Energy",
    category: "Bills",
    date: new Date("2024-08-10T11:30:00"),
    amount: 180.25,
  },
  {
    avatar: "elevate-education.jpg",
    name: "Elevate Education",
    category: "Bills",
    date: new Date("2024-07-28T16:20:00"),
    amount: 250.0,
  },
  {
    avatar: "ella-phillips.jpg",
    name: "Ella Phillips",
    category: "Entertainment",
    date: new Date("2024-08-05T19:00:00"),
    amount: 32.5,
  },
  {
    avatar: "emma-richardson.jpg",
    name: "Emma Richardson",
    category: "Dining Out",
    date: new Date("2024-07-30T13:45:00"),
    amount: 65.75,
  },
  {
    avatar: "ethan-clark.jpg",
    name: "Ethan Clark",
    category: "Personal Care",
    date: new Date("2024-08-12T10:30:00"),
    amount: 55.0,
  },
  {
    avatar: "flavor-fiesta.jpg",
    name: "Flavor Fiesta",
    category: "Dining Out",
    date: new Date("2024-07-25T19:30:00"),
    amount: 42.8,
  },
  {
    avatar: "green-plate-eatery.jpg",
    name: "Green Plate Eatery",
    category: "Dining Out",
    date: new Date("2024-08-08T12:15:00"),
    amount: 37.5,
  },
  {
    avatar: "harper-edwards.jpg",
    name: "Harper Edwards",
    category: "Entertainment",
    date: new Date("2024-07-20T21:00:00"),
    amount: 85.0,
  },
  {
    avatar: "james-thompson.jpg",
    name: "James Thompson",
    category: "Bills",
    date: new Date("2024-08-01T09:45:00"),
    amount: 150.0,
  },
  {
    avatar: "liam-hughes.jpg",
    name: "Liam Hughes",
    category: "Personal Care",
    date: new Date("2024-07-27T15:30:00"),
    amount: 40.0,
  },
  {
    avatar: "lily-ramirez.jpg",
    name: "Lily Ramirez",
    category: "Entertainment",
    date: new Date("2024-08-14T18:00:00"),
    amount: 70.25,
  },
  {
    avatar: "aqua-flow-utilities.jpg",
    name: "Aqua Flow Utilities",
    category: "Bills",
    date: new Date("2024-07-23T10:00:00"),
    amount: 95.5,
  },
  {
    avatar: "buzz-marketing-group.jpg",
    name: "Buzz Marketing Group",
    category: "Bills",
    date: new Date("2024-08-06T14:30:00"),
    amount: 500.0,
  },
  {
    avatar: "pixel-playground.jpg",
    name: "Pixel Playground",
    category: "Entertainment",
    date: new Date("2024-07-29T17:45:00"),
    amount: 45.99,
  },
  {
    avatar: "rina-sato.jpg",
    name: "Rina Sato",
    category: "Dining Out",
    date: new Date("2024-08-11T20:15:00"),
    amount: 58.75,
  },
  {
    avatar: "savory-bites-bistro.jpg",
    name: "Savory Bites Bistro",
    category: "Dining Out",
    date: new Date("2024-07-24T13:00:00"),
    amount: 82.3,
  },
  {
    avatar: "sebastian-cook.jpg",
    name: "Sebastian Cook",
    category: "Personal Care",
    date: new Date("2024-08-09T11:45:00"),
    amount: 65.0,
  },
  {
    avatar: "serenity-spa-and-wellness.jpg",
    name: "Serenity Spa and Wellness",
    category: "Personal Care",
    date: new Date("2024-07-31T16:30:00"),
    amount: 120.0,
  },
  {
    avatar: "sofia-peterson.jpg",
    name: "Sofia Peterson",
    category: "Entertainment",
    date: new Date("2024-08-13T19:15:00"),
    amount: 55.5,
  },
  {
    avatar: "spark-electric-solutions.jpg",
    name: "Spark Electric Solutions",
    category: "Bills",
    date: new Date("2024-07-26T09:30:00"),
    amount: 175.25,
  },
  {
    avatar: "sun-park.jpg",
    name: "Sun Park",
    category: "Entertainment",
    date: new Date("2024-08-07T18:45:00"),
    amount: 30.0,
  },
  {
    avatar: "swift-ride-share.jpg",
    name: "Swift Ride Share",
    category: "Entertainment",
    date: new Date("2024-07-21T12:30:00"),
    amount: 25.75,
  },
  {
    avatar: "technova-innovations.jpg",
    name: "Technova Innovations",
    category: "Bills",
    date: new Date("2024-08-04T10:15:00"),
    amount: 299.99,
  },
  {
    avatar: "urban-services-hub.jpg",
    name: "Urban Services Hub",
    category: "Bills",
    date: new Date("2024-07-19T15:45:00"),
    amount: 80.0,
  },
  {
    avatar: "william-harris.jpg",
    name: "William Harris",
    category: "Dining Out",
    date: new Date("2024-08-02T19:45:00"),
    amount: 95.25,
  },
  {
    avatar: "yuna-kim.jpg",
    name: "Yuna Kim",
    category: "Personal Care",
    date: new Date("2024-07-28T14:15:00"),
    amount: 50.0,
  },
  {
    avatar: "mason-martinez.jpg",
    name: "Mason Martinez",
    category: "Entertainment",
    date: new Date("2024-08-16T20:00:00"),
    amount: 89.99,
  },
  {
    avatar: "nimbus-data-storage.jpg",
    name: "Nimbus Data Storage",
    category: "Bills",
    date: new Date("2024-07-17T11:30:00"),
    amount: 149.99,
  },
  {
    avatar: "bytewise.jpg",
    name: "Bytewise",
    category: "Bills",
    date: new Date("2024-08-20T09:45:00"),
    amount: 79.99,
  },
  {
    avatar: "daniel-carter.jpg",
    name: "Daniel Carter",
    category: "Dining Out",
    date: new Date("2024-07-15T18:15:00"),
    amount: 62.5,
  },
  {
    avatar: "ecofuel-energy.jpg",
    name: "Ecofuel Energy",
    category: "Bills",
    date: new Date("2024-08-18T13:00:00"),
    amount: 195.75,
  },
  {
    avatar: "elevate-education.jpg",
    name: "Elevate Education",
    category: "Bills",
    date: new Date("2024-07-25T15:45:00"),
    amount: 275.0,
  },
  {
    avatar: "ella-phillips.jpg",
    name: "Ella Phillips",
    category: "Personal Care",
    date: new Date("2024-08-22T16:30:00"),
    amount: 48.0,
  },
  {
    avatar: "emma-richardson.jpg",
    name: "Emma Richardson",
    category: "Entertainment",
    date: new Date("2024-07-13T19:30:00"),
    amount: 75.25,
  },
  {
    avatar: "ethan-clark.jpg",
    name: "Ethan Clark",
    category: "Dining Out",
    date: new Date("2024-08-24T12:45:00"),
    amount: 68.9,
  },
  {
    avatar: "flavor-fiesta.jpg",
    name: "Flavor Fiesta",
    category: "Dining Out",
    date: new Date("2024-07-11T20:15:00"),
    amount: 52.3,
  },
  {
    avatar: "green-plate-eatery.jpg",
    name: "Green Plate Eatery",
    category: "Dining Out",
    date: new Date("2024-08-26T13:30:00"),
    amount: 41.75,
  },
  {
    avatar: "harper-edwards.jpg",
    name: "Harper Edwards",
    category: "Personal Care",
    date: new Date("2024-07-09T17:00:00"),
    amount: 95.0,
  },
  {
    avatar: "james-thompson.jpg",
    name: "James Thompson",
    category: "Entertainment",
    date: new Date("2024-08-28T18:45:00"),
    amount: 110.5,
  },
  {
    avatar: "liam-hughes.jpg",
    name: "Liam Hughes",
    category: "Dining Out",
    date: new Date("2024-07-07T14:15:00"),
    amount: 55.25,
  },
  {
    avatar: "lily-ramirez.jpg",
    name: "Lily Ramirez",
    category: "Bills",
    date: new Date("2024-08-30T10:30:00"),
    amount: 85.0,
  },
  {
    avatar: "aqua-flow-utilities.jpg",
    name: "Aqua Flow Utilities",
    category: "Bills",
    date: new Date("2024-07-05T09:00:00"),
    amount: 105.75,
  },
  {
    avatar: "buzz-marketing-group.jpg",
    name: "Buzz Marketing Group",
    category: "Bills",
    date: new Date("2024-09-01T11:15:00"),
    amount: 550.0,
  },
  {
    avatar: "pixel-playground.jpg",
    name: "Pixel Playground",
    category: "Entertainment",
    date: new Date("2024-07-03T19:45:00"),
    amount: 39.99,
  },
  {
    avatar: "rina-sato.jpg",
    name: "Rina Sato",
    category: "Personal Care",
    date: new Date("2024-09-03T15:30:00"),
    amount: 72.5,
  },
  {
    avatar: "savory-bites-bistro.jpg",
    name: "Savory Bites Bistro",
    category: "Dining Out",
    date: new Date("2024-07-01T12:45:00"),
    amount: 88.9,
  },
  {
    avatar: "sebastian-cook.jpg",
    name: "Sebastian Cook",
    category: "Entertainment",
    date: new Date("2024-09-05T20:00:00"),
    amount: 79.99,
  },
  {
    avatar: "serenity-spa-and-wellness.jpg",
    name: "Serenity Spa and Wellness",
    category: "Personal Care",
    date: new Date("2024-06-29T16:15:00"),
    amount: 135.0,
  },
  {
    avatar: "sofia-peterson.jpg",
    name: "Sofia Peterson",
    category: "Dining Out",
    date: new Date("2024-09-07T13:30:00"),
    amount: 67.25,
  },
  {
    avatar: "spark-electric-solutions.jpg",
    name: "Spark Electric Solutions",
    category: "Bills",
    date: new Date("2024-06-27T10:45:00"),
    amount: 190.5,
  },
  {
    avatar: "sun-park.jpg",
    name: "Sun Park",
    category: "Personal Care",
    date: new Date("2024-09-09T14:00:00"),
    amount: 45.0,
  },
  {
    avatar: "swift-ride-share.jpg",
    name: "Swift Ride Share",
    category: "Entertainment",
    date: new Date("2024-06-25T18:30:00"),
    amount: 35.75,
  },
  {
    avatar: "technova-innovations.jpg",
    name: "Technova Innovations",
    category: "Bills",
    date: new Date("2024-09-11T11:45:00"),
    amount: 319.99,
  },
  {
    avatar: "urban-services-hub.jpg",
    name: "Urban Services Hub",
    category: "Bills",
    date: new Date("2024-06-23T09:15:00"),
    amount: 95.0,
  },
  {
    avatar: "william-harris.jpg",
    name: "William Harris",
    category: "Entertainment",
    date: new Date("2024-09-13T19:30:00"),
    amount: 105.75,
  },
  {
    avatar: "yuna-kim.jpg",
    name: "Yuna Kim",
    category: "Dining Out",
    date: new Date("2024-06-21T13:00:00"),
    amount: 58.5,
  },
  {
    avatar: "mason-martinez.jpg",
    name: "Mason Martinez",
    category: "Personal Care",
    date: new Date("2024-09-15T15:45:00"),
    amount: 70.0,
  },
  {
    avatar: "nimbus-data-storage.jpg",
    name: "Nimbus Data Storage",
    category: "Bills",
    date: new Date("2024-06-19T10:30:00"),
    amount: 159.99,
  },
];

// const transactions: Transaction[] = [
//   {
//     name: "Savory Bites Bistro",
//     category: "Dining Out",
//     date: new Date(),
//     amount: -55.5,
//   },
//   {
//     name: "Daniel Carter",
//     category: "General",
//     date: new Date(),
//     amount: -42.3,
//   },
//   {
//     name: "Sun Park",
//     category: "General",
//     date: new Date(),
//     amount: 120,
//   },
//   {
//     name: "Ethan Clark",
//     category: "Dining Out",
//     date: new Date(),
//     amount: -32.5,
//   },
//   {
//     name: "Urban Services Hub",
//     category: "Dining Out",
//     date: new Date(),
//     amount: -65.0,
//   },
//   {
//     name: "James Thompson",
//     category: "Entertainment",
//     date: new Date(),
//     amount: -5,
//   },
//   {
//     name: "Pixel Playground",
//     category: "Entertainment",
//     date: new Date(),
//     amount: -10,
//   },
//   {
//     name: "Rina Sato",
//     category: "Entertainment",
//     date: new Date(),
//     amount: -10,
//   },
//   {
//     name: "Spark Electric Solutions",
//     category: "Bills",
//     date: new Date(),
//     amount: -100,
//   },
//   {
//     name: "Rina Sato",
//     category: "Bills",
//     date: new Date(),
//     amount: -50,
//   },
//   {
//     name: "Aqua Flow Utilities",
//     category: "Bills",
//     date: new Date(),
//     amount: -100,
//   },
//   {
//     name: "William Harris",
//     category: "Personal Care",
//     date: new Date(),
//     amount: -10,
//   },
//   {
//     name: "Serenity Spa & Wellness",
//     category: "Personal Care",
//     date: new Date(),
//     amount: -30,
//   },
//   {
//     name: "Serenity Spa & Wellness",
//     category: "Personal Care",
//     date: new Date(),
//     amount: -30,
//   },
// ];

//   "budgets": [
//     {
//       "category": "Entertainment",
//       "maximum": 50.0,
//       "theme": "#277C78"
//     },
//     {
//       "category": "Bills",
//       "maximum": 750.0,
//       "theme": "#82C9D7"
//     },
//     {
//       "category": "Dining Out",
//       "maximum": 75.0,
//       "theme": "#F2CDAC"
//     },
//     {
//       "category": "Personal Care",
//       "maximum": 100.0,
//       "theme": "#626070"
//     }
//   ],
//   "pots": [
//     {
//       "name": "Savings",
//       "target": 2000.0,
//       "total": 159.0,
//       "theme": "#277C78"
//     },
//     {
//       "name": "Concert Ticket",
//       "target": 150.0,
//       "total": 110.0,
//       "theme": "#626070"
//     },
//     {
//       "name": "Gift",
//       "target": 150.0,
//       "total": 110.0,
//       "theme": "#82C9D7"
//     },
//     {
//       "name": "New Laptop",
//       "target": 1000.0,
//       "total": 10.0,
//       "theme": "#F2CDAC"
//     },
//     {
//       "name": "Holiday",
//       "target": 1440.0,
//       "total": 531.0,
//       "theme": "#826CB0"
//     }
//   ]
// export const names = [];
